/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'createdAt' : IDL.Int,
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'upiTransactionRef' : IDL.Text,
});

export const idlService = IDL.Service({
  'calculate_total_amount' : IDL.Func(
      [IDL.Vec(OrderItem)],
      [IDL.Nat],
      ['query'],
    ),
  'cancel_order' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'create_order_item' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(OrderItem)],
      ['query'],
    ),
  'find_product_by_id' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'get_all_orders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'get_all_products' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'get_completed_orders_count' : IDL.Func([], [IDL.Nat], ['query']),
  'get_order_by_id' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'get_order_status' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'get_orders_by_phone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'get_orders_count' : IDL.Func([], [IDL.Nat], ['query']),
  'place_order' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(OrderItem),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'update_order_status' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'createdAt' : IDL.Int,
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'upiTransactionRef' : IDL.Text,
  });
  
  return IDL.Service({
    'calculate_total_amount' : IDL.Func(
        [IDL.Vec(OrderItem)],
        [IDL.Nat],
        ['query'],
      ),
    'cancel_order' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'create_order_item' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(OrderItem)],
        ['query'],
      ),
    'find_product_by_id' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'get_all_orders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'get_all_products' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'get_completed_orders_count' : IDL.Func([], [IDL.Nat], ['query']),
    'get_order_by_id' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'get_order_status' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'get_orders_by_phone' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'get_orders_count' : IDL.Func([], [IDL.Nat], ['query']),
    'place_order' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'update_order_status' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };