/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'customerName' : string,
  'status' : string,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'orderId' : bigint,
  'totalAmount' : bigint,
  'address' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
  'upiTransactionRef' : string,
}
export interface OrderItem {
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'totalPrice' : bigint,
}
export interface Product { 'id' : string, 'name' : string, 'price' : bigint }
export interface _SERVICE {
  'calculate_total_amount' : ActorMethod<[Array<OrderItem>], bigint>,
  'cancel_order' : ActorMethod<[bigint], boolean>,
  'create_order_item' : ActorMethod<[string, bigint], [] | [OrderItem]>,
  'find_product_by_id' : ActorMethod<[string], [] | [Product]>,
  'get_all_orders' : ActorMethod<[], Array<Order>>,
  'get_all_products' : ActorMethod<[], Array<Product>>,
  'get_completed_orders_count' : ActorMethod<[], bigint>,
  'get_order_by_id' : ActorMethod<[bigint], [] | [Order]>,
  'get_order_status' : ActorMethod<[bigint], string>,
  'get_orders_by_phone' : ActorMethod<[string], Array<Order>>,
  'get_orders_count' : ActorMethod<[], bigint>,
  'place_order' : ActorMethod<
    [string, string, string, Array<OrderItem>, bigint, string, string],
    bigint
  >,
  'update_order_status' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];